[theme]
# Primary accent for interactive elements
primaryColor = "#1abc9c"  # Tomato
# Background color for the main content area
backgroundColor = "#121212"  # Dark background
# Background color for the sidebar and the footer
secondaryBackgroundColor = "#1f1f1f"  # Slightly lighter dark background
# Color used for text in the main content area
textColor = "#e0e0e0"  # Light grey for readability
# Font used for all text elements
font = "sans serif"